### ISSUE TITLE
What is the rationale for changing button positioning wrt Studio plugin?

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-blockly-standalone#18]
This version moves the buttons together. What is the rationale behind this change?

The original layout in the VPL and Blockly in the Studio plugin was carefully designed by Maria to make it easy to use and layout information visually efficiently. For example the important buttons (start, stop) were centred and 50 % larger than the others.

Moreover, changing the positioning will break the habit of users, is there a good reason to do so?

**Comment by mbonani** [comment]
Order are not changed in respect of the blockly studio, the size perhaps more different in VPL but here it is also better responsive to the size of the screen. 

![capture-blockly](https://user-images.githubusercontent.com/1000934/34102364-221b89c8-e3e9-11e7-8f0a-b4907f2b698a.PNG)

**Comment by stephanemagnenat** [comment]
Sorry for unclarity, I meant positioning. I see the point of responsiveness.

I suggest to keep the start and stop buttons centered, as users probably are used to click here. One solution to keep both this and have responsiveness is to move the text "Thymio blockly" on the right, so that the expanding space is at the same place as in the plugin version. Also the added text takes a lot of space and does not bring value to the user (Thymio blockly is already written in the window title). The small version of the Thymio logo would certainly do fine.

**Comment by Vincebecker** [comment]
The layout is not the same there is less button and we want people to know whey are programming with Thymio Blockly (for the title).

We can add a space to separate the play and stop buttons. They will be visible enough this way.
We do not want to make the buttons bigger. We want to allow the users to have more space to program with a clean interface.

Users will start to program using the blockly interface in the left and then will go on the right to save or play. This is the logic behind this layout.

![image](https://user-images.githubusercontent.com/10742038/34102609-19500ff2-e3ea-11e7-9993-8b545cfdb0c3.png)

**Comment by stephanemagnenat** [comment]
I understand the rationale of making the Thymio branding more visible, but in the new layout it takes as much place as all active buttons which I think is far too much, as it is a static element that just takes space, especially when you say that you want people to have more space to program.

Also note that in most GUI programs *for example any office suite) the active buttons are on the left.  This new layout is unnatural. The original one by Maria, Jiwon and I was designed to be consistent with the existing programs, with the "file" buttons on the left and the "accessories" buttons on the right, with key active buttons in the centre just on top of the editing area.

Also note that users will click a lot on stop and go, and do a lot of back and forth between these buttons and the main screen. In that sense having them centred is good. The load/save/new buttons as well as the information and language change buttons are used infrequently.

**Comment by stephanemagnenat** [comment]
Also, as the Thymio logo already has the name Thymio, only the text "Blockly" could be written.

**Comment by Vincebecker** [comment]
You want it like this ?

![image](https://user-images.githubusercontent.com/10742038/34105402-5b6c80be-e3f4-11e7-8f61-b3aa60d9325c.png)

**Comment by stephanemagnenat** [comment]
Yes, exactly. On desktop-size layout you would have the space on the right for the Thymio logo and the Blockly text, and on tight layouts you can have it on two lines as currently.

**Comment by Vincebecker** [comment]
Like this ? 

![image](https://user-images.githubusercontent.com/10742038/34105972-b0270ae6-e3f6-11e7-8c54-c7439d73523e.png)

**Comment by stephanemagnenat** [comment]
Yes, or if you prefer (might be more logical for the switch to tight layout) you can have the text on the right of the language. Also I would not repeat the word Thymio, maybe you can have a cute Thymio Blockly logo that combines the Thymio logo with the word blockly on a second line?

**Comment by stephanemagnenat** [comment]
Also, when the layout is large enough you could have a little bit more space between the icons (like 8 pixels more), especially the two key ones in the center.

**Comment by stephanemagnenat** [comment]
Thanks for caring :-) This is also important as on Linux we still have the integrated Blockly (for technical reasons), it is important we minimize the discrepancy for classrooms and schools having both Linux and macOS/Windows, or for children in Geneva who have Linux at school but maybe Windows at home.

**Comment by Vincebecker** [comment]
Thinking of it I would rather put the logo in another corner (more like a signature). To me having it on the right is really not good at all.

![image](https://user-images.githubusercontent.com/10742038/34106442-7d61e958-e3f8-11e7-9e6e-4e36f1dc73e1.png)

**Comment by stephanemagnenat** [comment]
I fully agree, it is much better on the lower-right!

**Comment by stephanemagnenat** [comment]
Do you agree to change the layout for this one? (with a bit more spacing between icons for ex. 8 pixels)

**Comment by Vincebecker** [comment]
This is not my decision. I make proposition based on your comments but it is not my role to decide the final layout. Please see with the person in charge of the project and give me the final decision.

For me, since we want a fast beta-release, the best would be to try the first version I did with the users and change it if we have negative feedback.

But I will follow and trust the final decision.

**Comment by stephanemagnenat** [comment]
> For me, since we want a fast beta-release, the best would be to try the first version I did with the users and change it if we have negative feedback.

Although we want to go fast, we should not create a situation that will generate unnecessary complaints and support in the future.

I'll see with @mbonani for the final layout.

**Comment by mbonani** [comment]
As decide orally we implement the last layout

**Comment by Vincebecker** [comment]
Done.
