### ISSUE TITLE
Add about box

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-blockly-standalone#3]
An about box similar to the one of Aseba with the authors and contributors of Blockly should be added:

### Blockly authors

- Fabian Hahn
- Elisa Bernardoni
- Vincent Becker
- Maria María Beltrán
- Stéphane Magnenat

### based on Aseba by

- Stéphane Magnenat
- David Sherman
- Florian Vaussard
- Philippe Rétornaz

## Thank to

- Michael Bonani
- Corentin Jabot
- other translators

**Comment by mbonani** [comment]
vincent will work to do something similar that is existing in aseba

**Comment by stephanemagnenat** [comment]
And of course in Blockly authors it should be "Blockly for Thymio" author with a link to the Blockly website for the Google authors.

**Comment by stephanemagnenat** [comment]
We should also add EPFL-Mobots, Mobsya and Inria as institutions in thanks section.

**Comment by Vincebecker** [comment]
We added the about box. For now, it is only in french and in english.

**Comment by stephanemagnenat** [comment]
The about box is visually elegant, but it lacks a sentence mentioning that it is built on Aseba. Just after the main sentence, it should say:

"Thymio Blockly is based on the Aseba technology, learn more on aseba.io"

It is not acceptable that I have to constantly remind to properly cite Aseba.

**Comment by stephanemagnenat** [comment]
Also, this tab should have a link to the license. @cor3ntin can provide it.

**Comment by Vincebecker** [comment]
The about box is visually elegant, but it lacks a sentence mentioning that it is built on Aseba. In the about tab, it should say:

"Thymio Blockly is based on the Aseba technology, learn more on aseba.io"

> done.

Waiting for the link to the license. Any other things to add ?

**Comment by stephanemagnenat** [comment]
Now it seems good, thank you for the fast reaction!

**Comment by Vincebecker** [comment]
You're welcome. I am very sorry that I forgot to mention Aseba.
See you soon.

**Comment by cor3ntin** [comment]
@Vincebecker tell me when i need to rebuild a package. but the process being currently a bit painfull, I'd like to only do it once everything is complete or you are closer to the 1.6 release

**Comment by Vincebecker** [comment]
Sure @cor3ntin I will tell you.

**Comment by Vincebecker** [comment]
The about box messages are now translated.

**Comment by mbonani** [comment]
fixed
