### ISSUE TITLE
Icons are in low-resolution PNG

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-blockly-standalone#4]
Which is not Hi-DPI friendly. Icons should be in SVG as in Aseba.

**Comment by Vincebecker** [comment]
Sure, can you send me the svg files please ? (or a link)

**Comment by stephanemagnenat** [comment]
You can get them from here https://github.com/aseba-community/aseba/tree/master/clients/studio/images, click on a file then on "view raw" to download. `svgz` are `svg` files compressed with gzip.

**Comment by Vincebecker** [comment]
Done.
