### ISSUE TITLE
Icons changing size on hover is annoying

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/thymio-blockly-standalone#5]
Icons change size on hover, which is not very comfortable. They should have another type of highlight, less intrusive. Either as in Blockly/VPL in Aseba, or something else but that does not change the size.

**Comment by mbonani** [comment]
I find this ok and dynamic, I did not find thyt annoying

**Comment by stephanemagnenat** [comment]
No modern good design is doing this. It looks cheap and is disturbing. See [this entry](https://ux.stackexchange.com/questions/54013/should-button-icons-enlarge-on-hover) for an explanation why. Maria spend a lot of time creating a strong design style for VPL, please do not destroy it.

Regarding design, a good modern guidelines we use on mobile platforms for VPL is the [Google material guidelines](https://material.io/guidelines/).

**Comment by Vincebecker** [comment]
Done.
